import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import 'react-loading-skeleton/dist/skeleton.css'


const inter = Poppins({
  weight: ['400', '700', "200", "300", "600", "800"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Movedaba",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <main >
            <Toaster position="top-right" reverseOrder={true} />
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
