import VerifyEmail from "@/components/VerifyEmail";
import { Suspense } from "react";
export const metadata = {
  title: "Verify | Movedaba",
  description: "Generated by create next app",
};
const Verify = () => {
  return (
    <Suspense fallback={<div>Chargement...</div>}>
      <VerifyEmail />
    </Suspense>
  );
};

export default Verify;
